export const products = [{
        id: 1,
        title: "Gorro tipo baseball personalizado",
        price: 250,
        stock: 3,
        description: "Gorro personalizado según imagen o diseño de medidas similares",
        category: "vinilo",
        image: "https://res.cloudinary.com/dvritjbwt/image/upload/v1688949133/Dise%C3%B1o_sin_t%C3%ADtulo_8_l5buwp.png",
        stock: 5,
    },
    {
        id: 2,
        title: "Remera personalizada",
        price: 550,
        stock: 3,
        description: "Remera personalizada con vinilo a un color 30*10 centímetros aproximadamente",
        category: "vinilo",
        image: "https://res.cloudinary.com/dvritjbwt/image/upload/v1689123349/Dise%C3%B1o_sin_t%C3%ADtulo_1_xr2cc9.jpg",
        stock: 5,
    },
    {
        id: 3,
        title: "Puzzle personalizado",
        price: 350,
        stock: 3,
        description: "Puzzle de 15*30 centímetros personalizado a elección",
        category: "sublimado",
        image: "https://res.cloudinary.com/dvritjbwt/image/upload/v1688949862/diseno-mock-up-puzzle_1310-34_rlynzf.avif",
        stock: 5,
    },
    {
        id: 4,
        title: "Remera blanca dry-fit personalizada",
        price: 350,
        stock: 3,
        description: "Remera blanca personalizada según imagenes para cumpleaños, egresos o despedidas",
        category: "sublimado",
        image: "https://res.cloudinary.com/dvritjbwt/image/upload/v1688949443/Dise%C3%B1o_sin_t%C3%ADtulo_9_kjg5pp.png",
        stock: 5,
    },
]